### PR TITLE
Add particle section

### PR DESCRIPTION
**Pull request by gassmoeller**
Added a first draft of a section about particle optimizations. I will work on the text a bit more, but want to first get some numbers about performance (so far I only have numbers from ASPECT, but that includes unrelated optimizations as well, it would be nice to only measure the changes in deal.II).

### CODE REVIEW

**Comment by drwells** [comment]
Just to check - we copied and pasted your funding information from a previous release paper. Is it still right?

**Comment by drwells** [comment]
That list needed some other edits so I'll just handle it in the other PR.

**Comment by gassmoeller** [comment]
Thanks for the feedback. I have included your comments and added the performance table and discussion. Happy to include more feedback (should I cut the length of the section?), but from my point of view this now includes all important aspects. @kronbichler, @peterrum did I miss anything important?

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
Let me merge, and then I'll read and edit it next.

**Comment by bangerth** [comment]
Looked mostly good. I only edited small pieces. Thank you, good writing as always from you!

**Comment by kronbichler** [comment]
I had a look at the particle section and it looks great. As a matter of fact, I am impressed by the improvements that we made with these steps. :+1:

**Pull request merged**
